@echo off
echo Inicializando repositório Git...
git init
echo Adicionando arquivos...
git add .
echo Criando commit inicial...
git commit -m "Commit inicial do frontend"
echo Configurando branch main e adicionando remote...
git branch -M main
git remote add origin https://github.com/suportesantaprint-glitch/painel-faturamento.git
echo Fazendo push para o GitHub...
git push -u origin main
echo Push finalizado!
pause
